### ISSUE TITLE
add: moving aesthetics mapping into geom_function

### ISSUE THREAD

**Issue by TimWGY** [jtr13/ggformat#11]
Aesthetics mapping can be put into either ggplot call or the geom_function call. 
According to the cheatsheet, ggplot call contains only the data while geom_function has the specific mapping for that geom layer. For consistency and clarity in multiple-layer graph, it may help to move aesthetics mapping argument into geom_function when there is no foreseeable conflict or ambiguity.

TLDR, consider format this:
`... %>% 
  ggplot(aes(factor(cyl),mean_mpg)) +
  geom_col() +
  ...`
to be:
`... %>%
  ggplot() +
  geom_col(aes(factor(cyl),mean_mpg)) +
  ...`

**Comment by jtr13** [comment]
Sorry for the delay...just seeing this now. I think you're suggesting that the ggformat add-in move aesthetic mappings from `ggplot` to specific geoms. I actually prefer to keep the mappings global since then they don't have to be repeated for each geom separately. (More on this philosophy here: https://evangelinereynolds.netlify.app/post/mapping-aesthetics/). In addition, I would be hestitant to make material changes to the code; the purpose of the add-in is to simply to reformat.

**Comment by TimWGY** [comment]
Thanks for the reply! I now understand the philosophy behind current design. My initial thought is that putting aesthetic mappings into geom_functions would make the graph more customizable, but it makes sense to declare globally because we can always override the global grouping aesthetic in individual geom_functions.

**Comment by jtr13** [comment]
Thank you for your suggestion!

**Comment by TimWGY** [comment]
Thanks for the great course you taught!
